services:
  postgres:
    image: postgres:18-alpine
    container_name: ow-stadium-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: ow-stadium-api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
     image: nginx:alpine
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot
     depends_on:
       - app
  redis:
    image: redis:alpine
    container_name: ow-stadium-api-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
  app:
    build: .
    container_name: ow-stadium-api
    expose:
      - "7000"
    environment:
      DATABASE_URL: /run/secrets/db_url
      NODE_ENV: production
    depends_on:
      - postgres
    env_file:
      - .env.docker
  certbot:
    image: certbot/certbot
    container_name: ow-stadium-api-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: sleep 1d

secrets:
  db_password:
    file: db_password.txt
  db_url:
    file: db_url.txt

volumes:
  postgres_data:
  redis_data:
